adds `decl_info` base and `function_info`
cjdb/schreiber pull request #1
Opened 2023-07-04 07:35 UTC by cjdb

2023-07-04 12:49 UTC, seppeon requested changes
I've made some suggestions, it is already in a nice state!

I do have some questions though:

1. What will be done for unicode? (and does std::string cause issues there)
2. Will this be supporting attributes like `[[nodiscard]]` and `[[noreturn]]`?

That seems about it, been a pleasure to look over. 
PS. I haven't been able to build this yet, I only have clang16 on my computer, I will need to get 17.

2023-07-04 12:49 UTC, seppeon commented on include/schreiber/info.hpp
> +	using return_info = detail::sequenced_info<detail::sequences::returns>;
Just a check for myself, this is the string after the `\returns`:
```
\returns This string
```
right? And the return type, and parameter types will be extracted from the pointers to decl objects?

2023-07-04 12:49 UTC, seppeon commented on test/test_info.cpp
> +//
Is this from the googs?

2023-07-04 12:49 UTC, seppeon commented on test/test_info.cpp
> +	};
```suggestion
	auto template_param = []<typename T>(std::size_t i, std::string_view desc, std::type_identity<T>){
		return info::template_parameter_info(
			llvm::dyn_cast<T>(template_params->getParam(i)),
			desc);
	};
	auto template_parameters = std::vector{
		template_param(0, "Goat Island",        std::type_identity<clang::NonTypeTemplateParmDecl>{}),
		template_param(1, "Shells Town",        std::type_identity<clang::TemplateTypeParmDecl>{}),
		template_param(2, "Shimotsuki Village", std::type_identity<clang::TemplateTypeParmDecl>{}),
		template_param(3, "Orange Town",        std::type_identity<clang::TemplateTemplateParmDecl>{}),
		template_param(4, "Syrup Village",      std::type_identity<clang::TemplateTypeParmDecl>{}),
	};
```
Readability wasn't bad before, I thought this may be nicer.

2023-07-04 12:49 UTC, seppeon commented on source/info.cpp
> +//
Is this from google (or based on some source file template)?

2023-07-04 16:34 UTC, cjdb commented on include/schreiber/info.hpp
> +	using return_info = detail::sequenced_info<detail::sequences::returns>;
Yep! Everything code related is handled by Clang: we're just collecting content from comments here (so almost always strings or string-related).

2023-07-04 16:38 UTC, cjdb commented on source/info.cpp
> +//
This is an unfortunate consequence of working for Google in the US: they claim copyright ownership over **all** code that I write unless I get express permission.

2023-07-04 16:41 UTC, cjdb commented on test/test_info.cpp
> +	};
Thanks, I like it! Going to change just a little though, since I don't really like `type_identity`.

2023-07-04 16:47 UTC, cjdb commented on test/test_info.cpp
> +	};
Huh, TIL you can't explicitly pass template parameters when calling a lambda, which makes sense.

2023-07-04 17:22 UTC, cjdb commented
> What will be done for unicode? (and does std::string cause issues there)

This is a very good question that I don't have an answer to. libClang gives back `std::string` objects, so processing is rather limited in what can be done :(

> Will this be supporting attributes like [[nodiscard]] and [[noreturn]]?

The `decl_info` types don't need to: that's all a part of the declaration. I should document this a little more, but for now, the idea of these types is to capture what is expressed in the comments, then reconcile that with the canonical declaration.

> That seems about it, been a pleasure to look over.

Thank you for reviewing!

> PS. I haven't been able to build this yet, I only have clang16 on my computer, I will need to get 17.

The project [workflow] should have all the necessary steps to build :)

[workflow]: https://github.com/cjdb/schreiber/blob/8ee865a6a1521b51f2af2d6ddcb6d6a7a80ac058/.github/workflows/schreiber-ci.yml

2023-07-05 05:57 UTC, cjdb commented on test/test_info.cpp
> +  std::vector<std::string>{"-target", "x86_64-unknown-linux-gnu", "-std=c++20"};
Done, but to the whole file.

2023-07-05 05:57 UTC, cjdb commented on include/schreiber/info.hpp
> +		function_info(
Done.

2023-07-05 05:57 UTC, cjdb commented on include/schreiber/info.hpp
> +		function_info(
Done.

2023-07-06 06:49 UTC, merged